fix: support relative paths for icons
When using PyInstaller, importlib_resources.files("glue")
can return a relative path.
If this path is not resolved, it will lead to an error like:

  File "glue/icons/__init__.py", line 35, in icon_path
RuntimeError: Icon does not exist: /Users/maartenbreddels/github/spacetelescope/jdaviz/standalone/dist/jdaviz/_internal/glue_jupyter/bqplot/common/../../icons/glue_polygon.svg